### ISSUE TITLE
Missing composer-runtime-api

### ISSUE THREAD

**Issue by dompie** [Jean85/pretty-package-versions#40]
When trying to install I get the following error:

```
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for jean85/pretty-package-versions 2.0.4 -> satisfiable by jean85/pretty-package-versions[2.0.4].
    - jean85/pretty-package-versions 2.0.4 requires composer-runtime-api ^2.0.0 -> no matching package found.
```

There is no package called `composer-runtime-api` at packagist as of today.

**Comment by Jean85** [comment]
`composer-runtime-api` is a pseudo package that is exposed by Composer itself. It is used to lock onto a specific version of Composer, 2.0 in this case.

I suspect that this is a bug on Composer's side, probably fixed in https://github.com/composer/composer/pull/9941. What version of Composer are you using? 2.1.0? Can you try the latest? It works for me on 2.1.3.

**Comment by dompie** [comment]
Oh, good point! I was sure I have is the latest version. But it still was somehow stuck at 1.10.17.

Now it works great, thanks!
